---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: change.me.com
    init: true
    privileged: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: /home/pi/docker/foundry/usb
        target: /data 
    environment:
      - FOUNDRY_PASSWORD=changeme
      - FOUNDRY_USERNAME=changeme
      - FOUNDRY_ADMIN_KEY=changeme
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true 
      - FOUNDRY_UID=1000
      - FOUNDRY_GID=1000
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
